# Generated by Django 3.0.6 on 2020-06-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradePair', models.CharField(max_length=50)),
                ('openTime', models.IntegerField(unique=True)),
                ('openPrice', models.DecimalField(decimal_places=20, max_digits=40)),
                ('highPrice', models.DecimalField(decimal_places=20, max_digits=40)),
                ('lowPrice', models.DecimalField(decimal_places=20, max_digits=40)),
                ('closePrice', models.DecimalField(decimal_places=20, max_digits=40)),
                ('volume', models.DecimalField(decimal_places=20, max_digits=40)),
                ('closeTime', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['closeTime'],
            },
        ),
        migrations.CreateModel(
            name='ExecutedTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Decision', models.CharField(max_length=10)),
                ('coinData', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CoinData')),
            ],
        ),
        migrations.CreateModel(
            name='CoinPair',
            fields=[
                ('pair', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coinData', models.ManyToManyField(to='api.CoinData')),
            ],
        ),
    ]
