# Generated by Django 3.0.6 on 2020-06-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinpair',
            name='coinData',
        ),
        migrations.AddField(
            model_name='coindata',
            name='pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.CoinPair'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coindata',
            name='closeTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='openTime',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='coindata',
            unique_together={('closeTime', 'openTime', 'pair')},
        ),
        migrations.RemoveField(
            model_name='coindata',
            name='tradePair',
        ),
    ]
