# Generated by Django 3.0.6 on 2020-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200602_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coindata',
            options={'ordering': ['-closeTime']},
        ),
        migrations.AlterField(
            model_name='coindata',
            name='closePrice',
            field=models.DecimalField(decimal_places=28, max_digits=40),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='highPrice',
            field=models.DecimalField(decimal_places=28, max_digits=40),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='lowPrice',
            field=models.DecimalField(decimal_places=28, max_digits=40),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='openPrice',
            field=models.DecimalField(decimal_places=28, max_digits=40),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='volume',
            field=models.DecimalField(decimal_places=28, max_digits=40),
        ),
    ]
